# Creating A Machine Learning Model


>-  Data  Split
>-  Model Train
>-  Model Test
>-  Model Select
>-  Model Deploy(converting into '.ml')

In [1]:
#importing the necessary modules
import pandas as pd
import sklearn
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [2]:
# data read from local Directory
empData_1 = pd.read_csv("C:\\Users\\kiran\\Documents\\Project\\Data\\INX Clean Data.csv")
empData_1 = empData_1.iloc[:,1:]
empData_1.head()

Age  Gender  EducationBackground  MaritalStatus  EmpDepartment  EmpJobRole  \
0   32       1                    2              2              5          13   
1   47       1                    2              2              5          13   
2   40       1                    1              1              5          13   
3   41       1                    0              0              3           8   
4   60       1                    2              2              5          13   

   BusinessTravelFrequency  DistanceFromHome  EmpEducationLevel  \
0                        2                10                  3   
1                        2                14                  4   
2                        1                 5                  4   
3                        2                10                  4   
4                        2                16                  4   

   EmpEnvironmentSatisfaction  ...  EmpRelationshipSatisfaction  \
0                           4  ...                            4   
1                           4  ...                            4   
2                           4  ...                            3   
3                           2  ...                            2   
4                           1  ...                            4   

   TotalWorkExperienceInYears  TrainingTimesLastYear  EmpWorkLifeBalance  \
0                          10                      2                   2   
1                          20                      2                   3   
2                          20                      2                   3   
3                          23                      2                   2   
4                          10                      1                   3   

   ExperienceYearsAtThisCompany  ExperienceYearsInCurrentRole  \
0                            10                             7   
1                             7                             7   
2                            18                            13   
3                            21                             6   
4                             2                             2   

   YearsSinceLastPromotion  YearsWithCurrManager  Attrition  PerformanceRating  
0                        0                     8          0                  3  
1                        1                     7          0                  3  
2                        1                    12          0                  4  
3                       12                     6          0                  3  
4                        2                     2          0                  3  

[5 rows x 27 columns]

In [3]:
empData_1.shape

(1230, 27)

### Data Spliting

In [4]:
# Independent variables
X = empData_1.iloc[:,:-1]
X.iloc[1:2,9:]

EmpEnvironmentSatisfaction  EmpHourlyRate  EmpJobInvolvement  EmpJobLevel  \
1                           4             42                  3            2   

   EmpJobSatisfaction  NumCompaniesWorked  OverTime  EmpLastSalaryHikePercent  \
1                   1                   2         0                        12   

   EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
1                            4                          20   

   TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
1                      2                   3                             7   

   ExperienceYearsInCurrentRole  YearsSinceLastPromotion  \
1                             7                        1   

   YearsWithCurrManager  Attrition  
1                     7          0

In [5]:
y = empData_1.iloc[:,-1:]
y.head()

PerformanceRating
0                  3
1                  3
2                  4
3                  3
4                  3

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, recall_score, precision_score

#### SMOTE

In [8]:
#SMOTE installation required
#!pip install imblearn --user

In [9]:
from imblearn.over_sampling import SMOTE

Using TensorFlow backend.


In [10]:
smote=SMOTE(k_neighbors=4)
smote

SMOTE(k_neighbors=4, kind='deprecated', m_neighbors='deprecated', n_jobs=1,
      out_step='deprecated', random_state=None, ratio=None,
      sampling_strategy='auto', svm_estimator='deprecated')

In [11]:
X_smote,y_smote = smote.fit_sample(X_train,y_train)

### Training and Testing with Different Models to Measure the Accuracy

##  1. SVC - Support Vector Machines

In [44]:
##SVM / SVC - Support Vector Machine/Clasiifier
from sklearn.svm import SVC
model = SVC(C=5,kernel='rbf',probability=True)
svc = model

In [45]:
model.fit(X_train,y_train)
svc.fit(X_train,y_train)

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [46]:
model.fit(X_train,y_train)

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [47]:
y_predict = model.predict(X_test)

In [48]:
print("Model :",type(model))
print("Accuracy Score:",round(accuracy_score(y_predict,y_test)*100,2),'%','\n')
print(classification_report(y_test,y_predict))
confusion_matrix(y_test,y_predict)

Model : <class 'sklearn.svm.classes.SVC'>
Accuracy Score: 75.61 % 

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       0.00      0.00      0.00        52
           3       0.75      1.00      0.86       271
           4       0.00      0.00      0.00        38

    accuracy                           0.76       369
   macro avg       0.44      0.50      0.46       369
weighted avg       0.57      0.76      0.65       369



array([[  8,   0,   0,   0],
       [  0,   0,  52,   0],
       [  0,   0, 271,   0],
       [  0,   0,  38,   0]], dtype=int64)

In [70]:
low = empData_1.iloc[-25:-24,:-1]
good = empData_1.iloc[476:477,:-1]
exce = empData_1.iloc[53:54,:-1]
outst = empData_1.iloc[54:55,:-1]

# To check model efficiency , i/p [47,1,2,2,5,13,2,14,4,4,42,3,2,1,2,0,12,4,20,2,3,7,7,1,7,0] ,expected "Excellent"

a=model.predict_proba(outst)
a = pd.DataFrame(a)
a = a.values*100
a = a.round(2)
a = pd.DataFrame(a)
a.columns=["Low","Good","Excellent","Outstanding"]
a

Low   Good  Excellent  Outstanding
0  0.0  33.33      33.33        33.33

In [50]:
# 1 - 'low'
# 2 - 'Good'
# 3 - 'Excellent'
# 4 - 'Out standing'
#print(model.predict([[47,1,2,2,5,13,2,14,4,4,42,3,2,1,2,0,12,4,20,2,3,7,7,1,7,0]]))
b=model.predict(outst)
if b==1:
    print('low')
elif b==2:
    print('Good')
elif b==3:
    print('Excellent')
elif b==4:
    print('Out Standing')
else:
    print("un Predictable")
    

Out Standing


## 2. Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
model = RandomForestClassifier(n_estimators=100,random_state=102)
RF = model
model.fit(X_train,y_train)
RF.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=102,
                       verbose=0, warm_start=False)

In [53]:
y_predict = model.predict(X_test)

In [54]:
print("Model :",type(model))
print("Accuracy Score:",round(accuracy_score(y_predict,y_test)*100,2),'%','\n')
print(classification_report(y_test,y_predict))
confusion_matrix(y_test,y_predict)

Model : <class 'sklearn.ensemble.forest.RandomForestClassifier'>
Accuracy Score: 95.12 % 

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       0.88      0.88      0.88        52
           3       0.96      0.98      0.97       271
           4       0.97      0.84      0.90        38

    accuracy                           0.95       369
   macro avg       0.95      0.93      0.94       369
weighted avg       0.95      0.95      0.95       369



array([[  8,   0,   0,   0],
       [  0,  46,   6,   0],
       [  0,   5, 265,   1],
       [  0,   1,   5,  32]], dtype=int64)

In [69]:
low = empData_1.iloc[-25:-24,:-1]
good = empData_1.iloc[476:477,:-1]
exce = empData_1.iloc[53:54,:-1]
outst = empData_1.iloc[54:55,:-1]

# To check model efficiency , i/p [47,1,2,2,5,13,2,14,4,4,42,3,2,1,2,0,12,4,20,2,3,7,7,1,7,0] ,expected "Excellent"

a=model.predict_proba(good)
a = pd.DataFrame(a)
a = a.values*100
a = a.round(2)
a = pd.DataFrame(a)
a.columns=["Low","Good","Excellent","Outstanding"]
a

Low   Good  Excellent  Outstanding
0  0.0  33.33      33.33        33.33

## 3. XGBoost

In [56]:
#XGBoost installation required
#!pip install xgboost --user

In [57]:
from xgboost import XGBClassifier

In [58]:
model = XGBClassifier(n_estimators=50,learning_rate=0.1)
xgb = model
model.fit(X_train,y_train)
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=50, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [59]:
y_predict = model.predict(X_test)

In [60]:
print("Model :",type(model))
print("Accuracy Score:",round(accuracy_score(y_predict,y_test)*100,2),'%','\n')
print(classification_report(y_test,y_predict))
confusion_matrix(y_test,y_predict)

Model : <class 'xgboost.sklearn.XGBClassifier'>
Accuracy Score: 94.58 % 

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       0.85      0.88      0.87        52
           3       0.96      0.97      0.97       271
           4       0.94      0.87      0.90        38

    accuracy                           0.95       369
   macro avg       0.94      0.93      0.93       369
weighted avg       0.95      0.95      0.95       369



array([[  8,   0,   0,   0],
       [  0,  46,   6,   0],
       [  0,   7, 262,   2],
       [  0,   1,   4,  33]], dtype=int64)

In [68]:
low = empData_1.iloc[-25:-24,:-1]
good = empData_1.iloc[476:477,:-1]
exce = empData_1.iloc[53:54,:-1]
outst = empData_1.iloc[54:55,:-1]

# To check model efficiency , i/p [47,1,2,2,5,13,2,14,4,4,42,3,2,1,2,0,12,4,20,2,3,7,7,1,7,0] ,expected "Excellent"

a=model.predict_proba(outst)
a = pd.DataFrame(a)
a = a.values*100
a = a.round(2)
a = pd.DataFrame(a)
a.columns=["Low","Good","Excellent","Outstanding"]
a

Low   Good  Excellent  Outstanding
0  0.0  33.33      33.33        33.33

## 4. KNN - K Nearest Neighbour

In [62]:
from sklearn.neighbors import KNeighborsClassifier

In [63]:
model = KNeighborsClassifier(n_neighbors=3)
KNN = model
model.fit(X_train,y_train)
KNN.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [64]:
y_predict = model.predict(X_test)

In [65]:
print("Model :",type(model))
print("Accuracy Score:",round(accuracy_score(y_predict,y_test)*100,2),'%','\n')
print(classification_report(y_test,y_predict))
confusion_matrix(y_test,y_predict)

Model : <class 'sklearn.neighbors.classification.KNeighborsClassifier'>
Accuracy Score: 69.92 % 

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       0.19      0.15      0.17        52
           3       0.78      0.86      0.82       271
           4       0.44      0.21      0.29        38

    accuracy                           0.70       369
   macro avg       0.60      0.56      0.57       369
weighted avg       0.67      0.70      0.68       369



array([[  8,   0,   0,   0],
       [  0,   8,  42,   2],
       [  0,  29, 234,   8],
       [  0,   6,  24,   8]], dtype=int64)

In [67]:
low = empData_1.iloc[-25:-24,:-1]
good = empData_1.iloc[476:477,:-1]
exce = empData_1.iloc[53:54,:-1]
outst = empData_1.iloc[54:55,:-1]

# To check model efficiency , i/p [47,1,2,2,5,13,2,14,4,4,42,3,2,1,2,0,12,4,20,2,3,7,7,1,7,0] ,expected "Excellent"

a=model.predict_proba(outst)
a = pd.DataFrame(a)
a = a.values*100
a = a.round(2)
a = pd.DataFrame(a)
a.columns=["Low","Good","Excellent","Outstanding"]
a

Low   Good  Excellent  Outstanding
0  0.0  33.33      33.33        33.33

## 5. Decision Tree

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
model = DecisionTreeClassifier(max_depth=5,random_state=10)
DecisionTree= model
model.fit(X_train,y_train)
DecisionTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [38]:
y_predict = model.predict(X_test)

In [39]:
print("Model :",type(model))
print("Accuracy Score:",round(accuracy_score(y_predict,y_test)*100,2),'%','\n')
print(classification_report(y_test,y_predict))
confusion_matrix(y_test,y_predict)

Model : <class 'sklearn.tree.tree.DecisionTreeClassifier'>
Accuracy Score: 93.77 % 

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       0.82      0.90      0.86        52
           3       0.96      0.96      0.96       271
           4       0.91      0.84      0.88        38

    accuracy                           0.94       369
   macro avg       0.93      0.93      0.92       369
weighted avg       0.94      0.94      0.94       369



array([[  8,   0,   0,   0],
       [  0,  47,   5,   0],
       [  0,   9, 259,   3],
       [  0,   1,   5,  32]], dtype=int64)

In [40]:
low = empData_1.iloc[-25:-24,:-1]
good = empData_1.iloc[476:477,:-1]
exce = empData_1.iloc[53:54,:-1]
outst = empData_1.iloc[54:55,:-1]

# check model efficiency , input [47,1,2,2,5,13,2,14,4,4,42,3,2,1,2,0,12,4,20,2,3,7,7,1,7,0] ,expected "Excelent"

a=model.predict_proba(good)
a = pd.DataFrame(a)
a = a.values*100
a = a.round(2)
a = pd.DataFrame(a)
a.columns=["Low","Good","Excellent","Outstanding"]
a

Low   Good  Excellent  Outstanding
0  0.0  90.52       8.62         0.86

## Model Selection

#### All Model Accuracy Scores

In [72]:
print("Models sorted based on their Accuracy score. \n")

print("1. Random Forest Accuracy : ", 95.12)
print("2. XGBoost Accuracy       : ", 94.58)
print("3. Decision Tree Accuracy : ", 93.77)
print("4. SVC Accuracy           : ", 75.61)
print("5. KNN Accuracy           : ", 69.92)

Models sorted based on their Accuracy score. 

1. Random Forest Accuracy :  95.12
2. XGBoost Accuracy       :  94.58
3. Decision Tree Accuracy :  93.77
4. SVC Accuracy           :  75.61
5. KNN Accuracy           :  69.92


- Models with Good efficiency are:
>- Random Forest (Highest, '95.12')
>- XGBoost
>- Decision Tree
- With it's High Accuracy Score and Stability, Random Forest is Selected for Deployment.

## Model Deploy to .ml file

In [73]:
from sklearn.externals import joblib

In [43]:
#Model Dump
joblib.dump(RF,"Employee Rating.ml")

col1=empData_1.columns
col1=col1[:-1]
#columns Dump
joblib.dump(col1,"Features.pkg")

['Features.pkg']

# ---------- Please look into Data Visualization File ---------->